# Generated by Django 2.2 on 2019-04-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puppies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puppy',
            name='size',
        ),
    ]
